---
- name: Prepare provisioner
  gather_facts: yes
  hosts: provisioner
  roles:
    - vagrant-provisioner
    - gather-ssh-keys

- name: Configure switching infrastructure
  gather_facts: no
  hosts: switches
  roles:
    - switch

- name: Python minimal
  gather_facts: no
  become: yes
  hosts: servers
  roles:
    - { role: common-mutable/py-minimal }

- name: Apt proxy
  gather_facts: no
  become: yes
  hosts: kubernetes
  roles:
    - apt-proxy

- name: Vagrant remove df route
  gather_facts: no
  become: yes
  hosts: kubernetes
  roles:
    - vagrant

- name: Docker for k8s node
  gather_facts: no
  become: yes
  hosts: kubernetes
  roles:
    - { role: docker, tag: docker }

- name: Config for k8s master nodes
  gather_facts: yes
  become: yes
  hosts: master
  roles:
    - { role: kubernetes/master, tags: master }

- name: Config for k8s worker nodes
  gather_facts: yes
  become: yes
  hosts: worker
  roles:
    - { role: kubernetes/node, tags: worker }

- name: Create k8s resources
  become: yes
  hosts: master
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/admin.conf
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - { role: kubernetes/calico-rscreator }

- name: Calicoctl
  become: yes
  hosts: kubernetes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - { role: calicoctl }

- name: Calicoctl bgp config
  become: yes
  hosts: master
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - { role: calico-bgp-conf }
