apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  hostNetwork: true
  serviceAccountName: calicoctl
  containers:
  - name: calicoctl
    image: quay.io/calico/ctl:v3.2.3
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    env:
    - name: DATASTORE_TYPE
      value: kubernetes
