---

- shell: ". /etc/profile.d/dhcp_vars.sh && echo ${new_vagrant}"
  changed_when: False
  register: vagrant_sh

- set_fact:
    is_vagrant: "{{ vagrant_sh.stdout }}"

- name: Management ip
  shell: "ip addr show {{ mgmt_interface }} | grep -Eo 'inet (addr:)?([0-9]*\\.){3}[0-9]*' | grep -Eo '([0-9]*\\.){3}[0-9]*'"
  register: vagrant_mgt_host_ip
  changed_when: False
  when: is_vagrant

- name: Remove vagrant default route
  shell: ip r delete default via 10.0.2.2
  changed_when: False
  ignore_errors: True
  when: is_vagrant

- name: Add new default
  shell: "ip r add default via {{ vagrant_mgt_host_ip.stdout }}"
  changed_when: False
  ignore_errors: True
  when: is_vagrant
