---

- set_fact:
    proxy_conf: "{{proxy_env if proxy_env is defined else '{\"http_proxy\": \"\", \"https_proxy\": \"\"}'}}"

- name: Get calicoctl
  get_url:
    url: https://github.com/projectcalico/calicoctl/releases/download/v3.2.3/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    mode: 0755
  environment: "{{proxy_conf}}"
